### ISSUE TITLE
ExaCmech version for ExaConstit

### ISSUE THREAD

**Issue by NeelGKumar** [llnl/ExaConstit#22]
Hi,

I am trying to build ExaConstit and ran into an issue with the dependency on ExaCmech. ExaConstit suggests using tag 0.2.1 for Snls (dependency of ExaCmech) while ExaCmech is asking to build the "templated" branch of Snls. I am running into issues with both options, but before digging deeper wanted to know what version of Snls I should be using for ultimately building ExaConstit.

Also, I was building on Windows (Visual Studio). Is that a nonstarter for ExaConstit?

Thank you.

G Kumar

**Comment by rcarson3** [comment]
Hi @gkumar08, so you shouldn't need to do an out-of-source build of SNLS when building ExaCMech. If you look at the build script here: https://github.com/LLNL/ExaConstit/blob/exaconstit-dev/scripts/install/unix_install_example.sh you can see that the correct SNLS is automatically brought in by the `git submodule init && git submodule update` command. It does look like the readme in ExaCMech has the incorrect info there in regards to which branch to use. The template branch has already been merged into the develop SNLS branch so that info is no longer up to date.

Also, I've never built the full stack on Windows before. So, you're definitely entering into new territory there in regards whether or not our cmake files still work there. I would say you're best bet currently on Windows though will probably to use either WSL or WSL2 to compile things, since those systems should be more or less compatible with all of our tested unix builds.

**Comment by NeelGKumar** [comment]
@rcarson3 Thanks for the quick response. I should give it a try on Linux first then using your script.
